/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPreviewCardIndexRouteImport } from './routes/blog-preview-card/index'
import { Route as QrCodeComponentIndexRouteImport } from './routes/qr-code-component/index'
import { Route as SocialLinksProfileIndexRouteImport } from './routes/social-links-profile/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPreviewCardIndexRoute = BlogPreviewCardIndexRouteImport.update({
  id: '/blog-preview-card/',
  path: '/blog-preview-card/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeComponentIndexRoute = QrCodeComponentIndexRouteImport.update({
  id: '/qr-code-component/',
  path: '/qr-code-component/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialLinksProfileIndexRoute = SocialLinksProfileIndexRouteImport.update({
  id: '/social-links-profile/',
  path: '/social-links-profile/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog-preview-card/': typeof BlogPreviewCardIndexRoute
  '/qr-code-component/': typeof QrCodeComponentIndexRoute
  '/social-links-profile/': typeof SocialLinksProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog-preview-card': typeof BlogPreviewCardIndexRoute
  '/qr-code-component': typeof QrCodeComponentIndexRoute
  '/social-links-profile': typeof SocialLinksProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog-preview-card/': typeof BlogPreviewCardIndexRoute
  '/qr-code-component/': typeof QrCodeComponentIndexRoute
  '/social-links-profile/': typeof SocialLinksProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog-preview-card/'
    | '/qr-code-component/'
    | '/social-links-profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/blog-preview-card' | '/qr-code-component' | '/social-links-profile'
  id:
    | '__root__'
    | '/'
    | '/blog-preview-card/'
    | '/qr-code-component/'
    | '/social-links-profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogPreviewCardIndexRoute: typeof BlogPreviewCardIndexRoute
  QrCodeComponentIndexRoute: typeof QrCodeComponentIndexRoute
  SocialLinksProfileIndexRoute: typeof SocialLinksProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-preview-card/': {
      id: '/blog-preview-card/'
      path: '/blog-preview-card'
      fullPath: '/blog-preview-card/'
      preLoaderRoute: typeof BlogPreviewCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-component/': {
      id: '/qr-code-component/'
      path: '/qr-code-component'
      fullPath: '/qr-code-component/'
      preLoaderRoute: typeof QrCodeComponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-links-profile/': {
      id: '/social-links-profile/'
      path: '/social-links-profile'
      fullPath: '/social-links-profile/'
      preLoaderRoute: typeof SocialLinksProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogPreviewCardIndexRoute: BlogPreviewCardIndexRoute,
  QrCodeComponentIndexRoute: QrCodeComponentIndexRoute,
  SocialLinksProfileIndexRoute: SocialLinksProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
